FROM condaforge/mambaforge:latest

# Set environment variables to avoid interactive prompts during installation
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies needed for PETSc and other packages
RUN apt-get update && apt-get install -y \
    libblas-dev \
    liblapack-dev \
    libopenblas-dev \
    libmpich-dev \
    gfortran \
    wget \
    unzip \
    build-essential \
    && apt-get clean

# Create a non-root user for running the container
RUN useradd -m -s /bin/bash myuser

# Switch to the non-root user
USER myuser

# Set the working directory
WORKDIR /opt/app

# Create the fenics environment using mamba
RUN mamba create -n fenics python=3.9 fenics-dolfinx mpich && mamba clean -a -y

# Copy the requirements.txt and install dependencies into the fenics environment
COPY --chown=myuser:myuser requirements.txt /opt/app/requirements.txt
RUN /opt/conda/bin/mamba install --yes --file /opt/app/requirements.txt -n fenics  && \
    /opt/conda/bin/mamba clean -a -y

# Copy the rest of the app (with the proper ownership)
COPY --chown=myuser:myuser . /opt/app/

# Set the PATH to the Fenics environment and default command to start bash with environment activated
ENV PATH="/opt/conda/envs/fenics/bin:$PATH"

# Use bash in interactive mode
CMD ["bash", "-i"]
